import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: any) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col gap-10'>
          {props.children}
          {/* its undefined */}
          {props.modal}
        </div>
      </body>
    </html>
  )
}
